from __future__ import annotations

import base64
import os
import uuid
from pathlib import Path

from dotenv import load_dotenv
from fastapi import FastAPI, File, Form, Header, Request, UploadFile
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles

from bot_core import answer_question, CONFIG
from telegram import handle_telegram_update

ROOT = Path(__file__).resolve().parent
load_dotenv(ROOT / ".env")

app = FastAPI(title=CONFIG.get("bot_name", "Generated AI Chatbot"), version="0.1.0")
app.mount("/static", StaticFiles(directory=str(ROOT / "static")), name="static")


@app.get("/health")
def health():
    return {"ok": True, "bot": CONFIG.get("bot_name"), "slug": CONFIG.get("slug")}


@app.get("/", response_class=HTMLResponse)
def home():
    bot_name = CONFIG.get("bot_name", "AI Chatbot")
    description = CONFIG.get("description", "")
    vision = "true" if CONFIG.get("enable_vision") else "false"
    return f"""
<!doctype html><html lang='ko'><head><meta charset='utf-8'/><meta name='viewport' content='width=device-width, initial-scale=1'/>
<title>{bot_name}</title><link rel='stylesheet' href='/static/styles.css'/></head>
<body><main class='wrap'><section class='card'>
<p class='muted'>Generated by AI Agent Builder Workshop</p><h1>{bot_name}</h1><p>{description}</p>
<div class='row'><input id='message' placeholder='질문을 입력하세요. 예: AAPL 실적 리스크 요약해줘'/><button onclick='sendMsg()'>질문</button></div>
<div id='fileBox' style='display:{"block" if vision == "true" else "none"}'><input id='image' type='file' accept='image/*'/><p class='muted'>이미지를 올리면 GPT Vision 입력으로 전달합니다.</p></div>
<div id='chat' class='chat'></div></section></main>
<script>
const sid = localStorage.getItem('sid') || crypto.randomUUID(); localStorage.setItem('sid', sid);
async function sendMsg() {{
  const input = document.getElementById('message');
  const msg = input.value.trim(); if(!msg) return;
  append('user', msg); input.value='';
  const fd = new FormData(); fd.append('message', msg); fd.append('session_id', sid);
  const image = document.getElementById('image'); if(image && image.files[0]) fd.append('image', image.files[0]);
  append('bot', '생각 중...');
  const res = await fetch('/chat', {{method:'POST', body:fd}});
  const data = await res.json();
  document.querySelector('#chat .bot:last-child').textContent = data.answer || JSON.stringify(data);
}}
function append(role, text) {{ const div=document.createElement('div'); div.className='msg '+role; div.textContent=text; document.getElementById('chat').appendChild(div); }}
document.getElementById('message').addEventListener('keydown', e=>{{ if(e.key==='Enter') sendMsg(); }});
</script></body></html>"""


@app.post("/chat")
async def chat(message: str = Form(...), session_id: str = Form("default"), image: UploadFile | None = File(None)):
    image_b64 = None
    image_mime = None
    if image and image.filename:
        raw = await image.read()
        image_b64 = base64.b64encode(raw).decode("utf-8")
        image_mime = image.content_type or "image/png"
    result = answer_question(message=message, session_id=session_id, image_b64=image_b64, image_mime=image_mime)
    return JSONResponse(result)


@app.post("/telegram/webhook")
async def telegram_webhook(request: Request, x_telegram_bot_api_secret_token: str | None = Header(default=None)):
    expected = os.getenv("TELEGRAM_WEBHOOK_SECRET", "")
    if expected and x_telegram_bot_api_secret_token != expected:
        return JSONResponse({"ok": False, "error": "invalid secret"}, status_code=403)
    update = await request.json()
    return handle_telegram_update(update)
